import "../globals.css"
import { Geist, Geist_Mono } from "next/font/google"
import { setRequestLocale } from "next-intl/server"
import { NextIntlClientProvider } from "next-intl"
import { Metadata } from "next"
import { routing } from "@/i18n/routing"
import { notFound } from "next/navigation"
import { Locale } from "@/config"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

type LayoutProps = {
  children: React.ReactNode
  params: { locale: Locale }
}

export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound()
  }

  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
