import "../globals.css"
import { Geist as FontSans } from "next/font/google"
import { getMessages, setRequestLocale } from "next-intl/server"
import { NextIntlClientProvider } from "next-intl"
import { Metadata } from "next"
import { routing } from "@/i18n/routing"
import { notFound } from "next/navigation"
import { Locale } from "@/config"
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
})

type LayoutProps = {
  children: React.ReactNode
  params: Promise<{ locale: Locale }>
}

export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = await params

  if (!routing.locales.includes(locale as Locale)) {
    notFound()
  }

  setRequestLocale(locale)
  const messages = await getMessages()

  return (
    <html lang={locale} className="dark">
      <body
        className={cn(
          "max-w-7xl mx-auto border-x relative font-sans antialiased",
          fontSans.className
        )}
        style={{ backgroundColor: "oklch(21.03% .006 285.89)" }}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>{children}</NextIntlClientProvider>
      </body>
    </html>
  )
}