import { Geist, Geist_Mono } from "next/font/google"
import "../globals.css"
import { getMessages } from "next-intl/server"
import { NextIntlClientProvider } from "next-intl"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

type LayoutProps = {
  children: React.ReactNode
  params: { locale: string }
}

export default async function Layout({ children, params }: LayoutProps) {
  const { locale } = params
  const messages = await getMessages({ locale })
  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
