service: cohor-backend
frameworkVersion: '3'

configValidationMode: error

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  stage: local
  environment:
    ENVIRONMENT: ${self:custom.environment.ENVIRONMENT.${self:custom.stage}}

custom:
  artifact: "Cohor"
  environment: ${file(./src/main/serverless/configuration/environment.yaml)}
  region: "us-east-1"
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    httpPort: ${env:SERVERLESS_OFFLINE_HTTP_PORT, 3000}
    websocketPort: ${env:SERVERLESS_OFFLINE_WEBSOCKET_PORT, 3001}
    noPrependStageInUrl: true
    reloadHandler: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  - ${file(./src/main/serverless/functions/Example.yaml)}
          
useDotenv: true