service: cohor-backend
frameworkVersion: "3.40.0"

configValidationMode: error

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  stage: local
  ecr:
    images:
      main:
        uri: "${self:custom.ecr.imageURI}"
  environment:
    ENVIRONMENT: ${self:custom.environment.ENVIRONMENT.${self:custom.stage}}
    COHOR_APPLICATION_FRONTEND_ORIGINS: ${self:custom.environment.COHOR_APPLICATION_FRONTEND_ORIGINS.${self:custom.stage}}
    COHOR_API_GATEWAY_ENDPOINT_URI: ${self:custom.environment.COHOR_API_GATEWAY_ENDPOINT_URI.${self:custom.stage}}

custom:
  artifact: "Cohor"
  environment: ${file(./src/main/serverless/configuration/Environment.yaml)}
  region: "us-east-1"
  stage: ${opt:stage, self:provider.stage}
  ecr:
    imageURI: ${env:AWS_ECR_IMAGE_URI, "000000000000.dkr.ecr.region.amazonaws.com/namespace/repository:environment-commit-hash"}
  customDomain: ${file(./src/main/serverless/configuration/DomainManager.yaml)}
  roleAuthorizer:
    name: RoleAuthorizer
    identitySource: method.request.header.authorization
    resultTtlInSeconds: 0
    type: request
  googleAuthorizer:
    name: GoogleAuthorizer
    identitySource: method.request.header.Idtoken
    resultTtlInSeconds: 0
    type: request
  serverless-offline:
    httpPort: ${env:SERVERLESS_OFFLINE_HTTP_PORT, 3000}
    websocketPort: ${env:SERVERLESS_OFFLINE_WEBSOCKET_PORT, 3001}
    noPrependStageInUrl: true
    reloadHandler: true

plugins:
  - ./src/main/serverless/plugins/DockerOffline.js
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager

functions:
  - ${file(./src/main/authorization/RoleAuthorizerFunction.yaml)}
  - ${file(./src/main/authorization/GoogleAuthorizerFunction.yaml)}
  - ${file(./src/main/serverless/functions/PingFunction.yaml)}
  - ${file(./src/main/serverless/functions/auth/GetLoggedUser.yaml)}
  - ${file(./src/main/serverless/functions/auth/LoginFunction.yaml)}
  - ${file(./src/main/serverless/functions/auth/RegisterFunction.yaml)}
  - ${file(./src/main/serverless/functions/auth/ResendEmailFunction.yaml)}
  - ${file(./src/main/serverless/functions/auth/ValidateAccountFunction.yaml)}
  - ${file(./src/main/serverless/functions/auth/ValidationAccountSuccessfullyFunction.yaml)}
  - ${file(./src/main/serverless/functions/user/UpdateUserFunction.yaml)}
  - ${file(./src/main/serverless/functions/user/GetProfileImagePresignedParamsFunction.yaml)}
  - ${file(./src/main/serverless/functions/group/CreateGroupFunction.yaml)}
  - ${file(./src/main/serverless/functions/group/JoinGroupFunction.yaml)}
  - ${file(./src/main/serverless/functions/group/GetGroupFunction.yaml)}
  - ${file(./src/main/serverless/functions/group/GetGroupImagePresignedParamsFunction.yaml)}

useDotenv: true
