ENVIRONMENT:
  local: "Local"
  production: "Production"

COHOR_APPLICATION_FRONTEND_ORIGINS:
  local: ${env:COHOR_APPLICATION_FRONTEND_ORIGINS, "http://localhost:8080"}
  production: ""

COHOR_API_GATEWAY_ENDPOINT_URI:
  local: ${env:COHOR_API_GATEWAY_ENDPOINT_URI, "https://89eb-2800-40-3c-2eff-d01a-749f-668e-a543.ngrok-free.app"}
  production: ""